# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        krsanika:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/user
#            http_basic : ~
#            provider : game_provider
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    encoders:
        Mirage\UserBundle\Entity\User:
            algorithm: sha512
            iterations : 3
            encode_as_base64 : false
    providers:
        in_memory:
            users:
                admin : {password: krsanika, roles: [ 'ROLE_ADMIN'] }
        game_provider:
            entity:
                class: Mirage\UserBundle\Entity\User
                property: username
                manager_name: user1_admin

    access_control:
        - { path: ^/apocripha, roles: ROLE_ADMIN }