# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    memcache_config :
        host : "%memcache_host%"
        port : "%memcache_port%"

services:
    mirage.topic_service:
         class: Mirage\UserBundle\Topic\CroixTopic
         tags:
             - { name: gos_web_socket.topic }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
